name: away_review
description: "A new Flutter project."
publish_to: 'none' 
version: 0.0.5+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=2.8.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.15.5
  cupertino_icons: ^1.0.6
  firebase_analytics: ^10.8.6
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.15
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/google_fonts/
