name: Create release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the tag
        id: get_tag
        run: echo "::set-output name=tag::${{ github.ref }}"
        env:
          TAG_REF: ${{ github.ref }}

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '15'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.x'

      - name: Create Firebase options file
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS_BASE64 }}" | base64 --decode > lib/firebase_options.dart

      - name: Download dependencies
        run: flutter pub get

      - name: Build android
        run: flutter build apk --release --build-number=${{ github.run_number }} --split-per-abi

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          prerelease: false
          tag: ${{ steps.get_tag.outputs.tag }}
          name: ${{ steps.get_tag.outputs.tag }} release
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          body: |
            This is a release for ${{ steps.get_tag.outputs.tag }}
            